services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    networks:
      - task-network

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:5000"
    depends_on:
      - database
    networks:
      - task-network
    environment:
      - DATABASE_URL=postgresql://${LIMITED_USER}:${LIMITED_PASSWORD}@$database:${POSTGRES_PORT}/${POSTGRES_DB}

  database:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql
      - ./database/initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - LIMITED_USER=${LIMITED_USER}
      - LIMITED_PASSWORD=${LIMITED_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - task-network

  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
      # !!! Спільний том для сертифікатів !!!
      # - ./certbot/conf:/etc/letsencrypt
      # - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
      # - certbot
    networks:
      - task-network

  # Цей контейнер призначений для одноразового запуску (генерація сертифікатів),
  # або може бути налаштований як cron-завдання для автоматичного поновлення.
  # Викоистовується тільки для прода. Для локального використовуються самопідписані сертифікати.
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/logs:/var/log/letsencrypt
  #     # !!! Спільний том для сертифікатів !!!
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   command: certonly --webroot -w /var/www/certbot --force-renewal -d ${PROJECT_DOMAIN} -d www.${PROJECT_DOMAIN} -m topa1978@gmail.com --agree-tos --no-eff-email

  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
    networks:
      - task-network

  grafana:
    image: grafana/grafana
    ports:
      - "3033:3000"
    depends_on:
      - prometheus
    networks:
      - task-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - task-network

  logstash:
    build: ./logstash
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    networks:
      - task-network

  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - task-network

  filebeat:
      build: ./filebeat
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
      depends_on:
        - logstash
      networks:
        - task-network

volumes:
  db_data:

networks:
  task-network:
    driver: bridge
